# Generated by Django 3.2 on 2021-04-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0002_auto_20210413_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='dimness',
        ),
        migrations.RemoveField(
            model_name='light',
            name='roomLoc',
        ),
    ]
