# Generated by Django 3.2 on 2021-04-22 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0003_auto_20210421_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='dimness',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
