# Generated by Django 3.2 on 2021-04-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0004_light_dimness'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='state',
            field=models.BooleanField(default=0),
        ),
    ]
