# Generated by Django 3.2 on 2021-04-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0006_auto_20210424_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='code1',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='code2',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='code3',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='code4',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='lock',
            name='code1',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='lock',
            name='code2',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='lock',
            name='code3',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='lock',
            name='code4',
            field=models.CharField(max_length=4),
        ),
    ]
