# Generated by Django 3.2 on 2021-04-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0007_auto_20210424_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='code1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='code2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='code3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='code4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lock',
            name='code1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lock',
            name='code2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lock',
            name='code3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lock',
            name='code4',
            field=models.IntegerField(),
        ),
    ]
