# Generated by Django 3.2 on 2021-04-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0008_auto_20210424_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='state',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='lock',
            name='state',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='code1',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='code2',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='code3',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='code4',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='lock',
            name='code1',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='lock',
            name='code2',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='lock',
            name='code3',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='lock',
            name='code4',
            field=models.IntegerField(max_length=4),
        ),
    ]
