# Generated by Django 3.2 on 2021-04-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0011_light_lighttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='lightType',
            field=models.CharField(choices=[('default light', 'default light'), ('floor lamp', 'floor lamp'), ('table lamp', 'table lamp'), ('ceiling light', 'ceiling light')], default='default light', max_length=20),
        ),
    ]
